module.exports = {
    disableEmoji: true,
    list: [
        'add',
        'config',
        'conflicts',
        'design',
        'dependency',
        'docs',
        'files',
        'fix',
        'idea',
        'improve',
        'log',
        'move',
        'performance',
        'refactor',
        'review',
        'security',
        'style',
        'test',
        'tracking',
        'update',
        'wip',
    ],
    maxMessageLength: 128,
    minMessageLength: 3,
    questions: ['type', 'subject'],
    scopes: ['None', 'API', 'Feature', 'Setup', 'Type Definitions'],

    types: {
        add: { description: 'Add new features', emoji: '✨', value: 'add' },
        basicFix: { description: 'Bug fixes and basic problem-solving', emoji: '🛠️', value: 'basicFix' },
        config: { description: 'Config change', emoji: ' ⚙', value: 'config' },
        conflicts: { description: 'Conflicts', emoji: '💢', value: 'conflicts' },
        design: { description: 'Design changes only', emoji: '🎨', value: 'design' },
        dependency: { description: 'Add new dependency', emoji: '📦', value: 'dependency' },
        docs: { description: 'Documentation', emoji: '📚', value: 'docs' },
        files: { description: 'Folder manipulation', emoji: '🗂️', value: 'files' },
        fix: { description: 'Bug fixes', emoji: '🐛', value: 'fix' },
        idea: { description: 'Implement and code idea', emoji: '💡', value: 'idea' },
        improve: { description: 'Feature improvements', emoji: '👍', value: 'improve' },
        log: { description: 'Logging and tracking', emoji: '📊', value: 'log' },
        move: { description: 'File movement', emoji: '🚚', value: 'move' },
        performance: { description: 'Performance improvements', emoji: '🚀', value: 'performance' },
        refactor: { description: 'Refactoring', emoji: '♻️', value: 'refactor' },
        review: { description: 'Code reading and questions', emoji: '🧐', value: 'review' },
        security: { description: 'Security', emoji: '🛡️', value: 'security' },
        style: { description: 'Lint error fixes and code style fixes', emoji: '👕', value: 'style' },
        test: { description: 'Fix/improve testing and CI', emoji: '🧪', value: 'test' },
        tracking: { description: 'Add analytics or tracking code', emoji: '📈', value: 'tracking' },
        update: { description: 'Update dependency packages, etc.', emoji: '🆙', value: 'update' },
        wip: { description: 'WIP (Work in Progress)', emoji: '🚧', value: 'wip' }
    }
};
